// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package blog_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Ip                   int64    `protobuf:"varint,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	ProfilePhoto         string   `protobuf:"bytes,5,opt,name=profile_photo,json=profilePhoto,proto3" json:"profile_photo,omitempty"`
	RegistrationTime     string   `protobuf:"bytes,6,opt,name=registration_time,json=registrationTime,proto3" json:"registration_time,omitempty"`
	Birthday             string   `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Phone                string   `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname             string   `protobuf:"bytes,9,opt,name=nickname,proto3" json:"nickname,omitempty"`
	CreatedAt            string   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Pwd                  string   `protobuf:"bytes,11,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *User) GetIp() int64 {
	if m != nil {
		return m.Ip
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetProfilePhoto() string {
	if m != nil {
		return m.ProfilePhoto
	}
	return ""
}

func (m *User) GetRegistrationTime() string {
	if m != nil {
		return m.RegistrationTime
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "blog.service.user.User")
	proto.RegisterType((*Request)(nil), "blog.service.user.Request")
	proto.RegisterType((*Response)(nil), "blog.service.user.Response")
	proto.RegisterType((*Error)(nil), "blog.service.user.Error")
	proto.RegisterType((*Token)(nil), "blog.service.user.Token")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdf, 0x6a, 0x13, 0x41,
	0x14, 0xc6, 0x9b, 0xfd, 0x93, 0x3f, 0x27, 0x56, 0xd2, 0x83, 0xe2, 0x10, 0x11, 0xc2, 0x7a, 0x53,
	0x28, 0x46, 0xa9, 0x97, 0x52, 0x30, 0x84, 0x50, 0x10, 0x2f, 0xca, 0xda, 0x7a, 0x1b, 0x36, 0xbb,
	0xc7, 0x66, 0xc8, 0x66, 0x67, 0x3b, 0x33, 0x5b, 0xf1, 0x4d, 0x7c, 0x03, 0x9f, 0xc2, 0x77, 0x93,
	0x39, 0xbb, 0x91, 0x80, 0x49, 0xc5, 0xe0, 0x4d, 0x32, 0xdf, 0x77, 0x7e, 0x73, 0x38, 0xfb, 0xcd,
	0xce, 0xc2, 0xd3, 0x52, 0x2b, 0xab, 0x5e, 0x57, 0x86, 0x34, 0xff, 0x8c, 0x59, 0xe3, 0xc9, 0x22,
	0x57, 0xb7, 0x63, 0x43, 0xfa, 0x5e, 0xa6, 0x34, 0x76, 0x85, 0xe8, 0x87, 0x07, 0xc1, 0x8d, 0x21,
	0x8d, 0x8f, 0xc1, 0x93, 0x99, 0x68, 0x8d, 0x5a, 0xa7, 0xbd, 0xd8, 0x93, 0x19, 0x0a, 0xe8, 0x24,
	0x69, 0xaa, 0xaa, 0xc2, 0x0a, 0x8f, 0xcd, 0x8d, 0x64, 0xb2, 0x14, 0xfe, 0xa8, 0x75, 0xea, 0xc7,
	0x9e, 0x2c, 0xf1, 0x09, 0x84, 0xb4, 0x4e, 0x64, 0x2e, 0x02, 0xe6, 0x6a, 0x81, 0x2f, 0xe1, 0xb8,
	0xd4, 0xea, 0x8b, 0xcc, 0x69, 0x5e, 0x2e, 0x95, 0x55, 0x22, 0xe4, 0xea, 0xa3, 0xc6, 0xbc, 0x72,
	0x1e, 0x9e, 0xc1, 0x89, 0xa6, 0x5b, 0x69, 0xac, 0x4e, 0xac, 0x54, 0xc5, 0xdc, 0xca, 0x35, 0x89,
	0x36, 0x83, 0x83, 0xed, 0xc2, 0xb5, 0x5c, 0x13, 0x0e, 0xa1, 0xbb, 0x90, 0xda, 0x2e, 0xb3, 0xe4,
	0x9b, 0xe8, 0x30, 0xf3, 0x5b, 0xbb, 0x19, 0xca, 0xa5, 0x2a, 0x48, 0x74, 0xeb, 0x19, 0x58, 0xb8,
	0x1d, 0x85, 0x4c, 0x57, 0x45, 0xb2, 0x26, 0xd1, 0xab, 0x77, 0x6c, 0x34, 0xbe, 0x00, 0x48, 0x35,
	0x25, 0x96, 0xb2, 0x79, 0x62, 0x05, 0x70, 0xb5, 0xd7, 0x38, 0x13, 0x8b, 0x03, 0xf0, 0xcb, 0xaf,
	0x99, 0xe8, 0xb3, 0xef, 0x96, 0x51, 0x0f, 0x3a, 0x31, 0xdd, 0x55, 0x64, 0x6c, 0xf4, 0xbd, 0x05,
	0xdd, 0x98, 0x4c, 0xa9, 0x0a, 0x43, 0x78, 0x06, 0x81, 0x4b, 0x92, 0xa3, 0xeb, 0x9f, 0x3f, 0x1b,
	0xff, 0x91, 0xf1, 0xd8, 0xe5, 0x1b, 0x33, 0x84, 0xaf, 0x20, 0x74, 0xff, 0x46, 0x78, 0x23, 0xff,
	0x21, 0xba, 0xa6, 0xf0, 0x0d, 0xb4, 0x49, 0x6b, 0xa5, 0x8d, 0xf0, 0x99, 0x17, 0x3b, 0xf8, 0x99,
	0x03, 0xe2, 0x86, 0x8b, 0x2e, 0x20, 0x64, 0x03, 0x11, 0x82, 0x54, 0x65, 0xc4, 0x63, 0x85, 0x31,
	0xaf, 0x71, 0x04, 0xfd, 0x8c, 0x4c, 0xaa, 0x65, 0xe9, 0x42, 0x6d, 0xce, 0x75, 0xdb, 0x8a, 0x08,
	0xc2, 0x6b, 0xb5, 0xa2, 0xc2, 0x05, 0x6a, 0xdd, 0xa2, 0x79, 0x23, 0x6a, 0xe1, 0xdc, 0xfb, 0x24,
	0x97, 0x19, 0x6f, 0xed, 0xc6, 0xb5, 0xf8, 0xf7, 0x29, 0xcf, 0x7f, 0x06, 0xd0, 0x77, 0xcf, 0xf9,
	0xa9, 0x46, 0xf0, 0x3d, 0xb4, 0xa7, 0x1c, 0x3d, 0xee, 0x4b, 0x64, 0xf8, 0x7c, 0x47, 0x61, 0x73,
	0x06, 0xd1, 0x11, 0x5e, 0x80, 0x7f, 0x49, 0xf6, 0xe0, 0xed, 0x53, 0x68, 0x5f, 0x92, 0x9d, 0xe4,
	0x39, 0x0e, 0x77, 0x82, 0x7c, 0xee, 0x7f, 0x6b, 0xf2, 0x0e, 0x82, 0x49, 0x65, 0x97, 0xfb, 0x87,
	0xd8, 0x15, 0x0c, 0xc7, 0x1d, 0x1d, 0xe1, 0x0c, 0x8e, 0x3f, 0xbb, 0x34, 0x13, 0x4b, 0xf5, 0x09,
	0xec, 0x85, 0x1f, 0x6c, 0xf3, 0x11, 0x70, 0xba, 0xa4, 0x74, 0x75, 0x53, 0xc8, 0xbb, 0x8a, 0x26,
	0xcd, 0x95, 0x3d, 0x34, 0x96, 0x0f, 0x30, 0xd8, 0xea, 0x36, 0xe3, 0x8b, 0xfd, 0x7f, 0x7a, 0x5d,
	0xf1, 0x05, 0x3d, 0xb0, 0xd7, 0xa2, 0xcd, 0xdf, 0xb3, 0xb7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xce, 0x3a, 0x1b, 0xb4, 0xe8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	// 创建用户
	Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// 通过主键ID获取用户信息
	Get(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// 获取所有的用户信息
	GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 认证接口
	Auth(ctx context.Context, in *User, opts ...client.CallOption) (*Token, error)
	// 密码校验
	ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error)
	CheckUniqueAccount(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	CheckUniqueEmail(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	CheckUniquePhone(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "blog.service.user"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.GetAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Auth(ctx context.Context, in *User, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Auth", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.ValidateToken", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CheckUniqueAccount(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.CheckUniqueAccount", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CheckUniqueEmail(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.CheckUniqueEmail", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CheckUniquePhone(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.CheckUniquePhone", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// 创建用户
	Create(context.Context, *User, *Response) error
	// 通过主键ID获取用户信息
	Get(context.Context, *User, *Response) error
	// 获取所有的用户信息
	GetAll(context.Context, *Request, *Response) error
	// 认证接口
	Auth(context.Context, *User, *Token) error
	// 密码校验
	ValidateToken(context.Context, *Token, *Token) error
	CheckUniqueAccount(context.Context, *User, *Response) error
	CheckUniqueEmail(context.Context, *User, *Response) error
	CheckUniquePhone(context.Context, *User, *Response) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) Create(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.Create(ctx, in, out)
}

func (h *UserService) Get(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.Get(ctx, in, out)
}

func (h *UserService) GetAll(ctx context.Context, in *Request, out *Response) error {
	return h.UserServiceHandler.GetAll(ctx, in, out)
}

func (h *UserService) Auth(ctx context.Context, in *User, out *Token) error {
	return h.UserServiceHandler.Auth(ctx, in, out)
}

func (h *UserService) ValidateToken(ctx context.Context, in *Token, out *Token) error {
	return h.UserServiceHandler.ValidateToken(ctx, in, out)
}

func (h *UserService) CheckUniqueAccount(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.CheckUniqueAccount(ctx, in, out)
}

func (h *UserService) CheckUniqueEmail(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.CheckUniqueEmail(ctx, in, out)
}

func (h *UserService) CheckUniquePhone(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.CheckUniquePhone(ctx, in, out)
}
